### ISSUE TITLE
Split the Linux column into .deb and .tar.gz columns

### ISSUE THREAD

**Issue by ssokolow** [ssokolow/lgogd_uri#1]
...because it's the most natural way to easily allow momentary exceptions to the policy in `config.cfg`.

As with `platforms`, I'll default it based on `no-deb` and `no-targz` so people who don't want it can ignore it and have the same behaviour as before.

Given that the .debs are intended for Ubuntu, I think I'll use the existing Linux icon for the .tar.gz column and this icon for the .deb column: ![ubuntu](https://cloud.githubusercontent.com/assets/46915/7279881/21a19c3e-e8ed-11e4-81b8-854fabd3ecff.png)

**Comment by vv221** [comment]
Now that GOG dropped .tar.gz/.deb archives for Linux games in favour of a unique .sh MojoSetup installer, I guess this entry could be closed.

**Comment by ssokolow** [comment]
Yeah. I've been very busy and haven't had time to pay attention to things tagged enhancement.
